/**
 * Repositório de leitura: monta o estado completo da operação a partir do banco.
 * Só esta camada conhece o Supabase; telas e serviços usam entidades do domínio.
 */
import { conferirErro } from "@/data/erros";
import { supabase } from "@/integrations/supabase/client";
import {
  paraAgente,
  paraApelido,
  paraCobranca,
  paraDocumento,
  paraEvidencia,
  paraEvento,
  paraFoto,
  paraImportacao,
  paraLocadora,
  paraAuditoria,
  paraCancelamento,
  paraNotificacao,
  paraItemRemuneracao,
  paraLancamento,
  paraOrdem,
  paraPagamento,
  paraServico,
  paraTabelaRemuneracao,
  paraMoto,
  paraVistoria,
  paraEvidenciaVistoria,
  paraEventoVistoria,
  paraItemChecklistCatalogo,
  paraItemVistoria,
  paraAvariaVistoria,
  paraDistribuicao,
  paraEventoDistribuicao,
  paraUsuario,
} from "@/domain/entities/mapeadores";
import type { Banco } from "@/domain/types";

export const BANCO_VAZIO: Banco = {
  usuarios: [],
  locadoras: [],
  agentes: [],
  ordens: [],
  fotos: [],
  historico: [],
  importacoes: [],
  documentos: [],
  pagamentos: [],
  evidencias: [],
  cobrancas: [],
  apelidos: [],
  servicos: [],
  tabelas: [],
  itens: [],
  lancamentos: [],
  configuracoes: {},
  auditoria: [],
  notificacoes: [],
  cancelamentos: [],
  motos: [],
  vistorias: [],
  evidenciasVistoria: [],
  historicoVistoria: [],
  catalogoChecklist: [],
  itensVistoria: [],
  avariasVistoria: [],
  distribuicoes: [],
  eventosDistribuicao: [],
};

/** Tabelas monitoradas em tempo real. */
export const TABELAS_REALTIME = [
  "locadoras",
  "agentes",
  "profiles",
  "user_roles",
  "ordens",
  "ordem_fotos",
  "ordem_historico",
  "importacoes",
  "servicos",
  "agente_documentos",
  "pagamentos_agente",
  "ordem_evidencias",
  "ordem_cobrancas",
  "locadora_apelidos",
  "tabelas_remuneracao",
  "itens_remuneracao",
  "lancamentos_agente",
  "configuracoes",
  "auditoria",
  "notificacoes",
  "cancelamentos_ordem",
  "motos",
  "vistorias",
  "vistoria_evidencias",
  "vistoria_historico",
  "vistoria_checklist_itens",
  "vistoria_itens",
  "vistoria_avarias",
  "distribuicoes",
  "distribuicao_eventos",
] as const;

function conferir<T>(resposta: { data: T | null; error: { message: string } | null }): T {
  conferirErro(resposta.error, "sincronização");
  return (resposta.data ?? []) as T;
}

export async function carregarBanco(): Promise<Banco> {
  const [
    locadoras,
    agentes,
    perfis,
    papeis,
    ordens,
    fotos,
    historico,
    importacoes,
    documentos,
    pagamentos,
    evidencias,
    cobrancas,
    apelidos,
    tabelas,
    itens,
    lancamentos,
    configuracoes,
    auditoria,
    servicos,
    notificacoes,
    cancelamentos,
    motos,
    vistorias,
    evidenciasVistoria,
    historicoVistoria,
    catalogoChecklist,
    itensVistoria,
    avariasVistoria,
    distribuicoes,
    eventosDistribuicao,
  ] = await Promise.all([
    supabase.from("locadoras").select("*").order("criada_em"),
    supabase.from("agentes").select("*").order("criado_em"),
    supabase.from("profiles").select("*").order("criado_em"),
    supabase.from("user_roles").select("user_id, role"),
    supabase.from("ordens").select("*").order("criada_em", { ascending: false }),
    // Só os metadados: a imagem (data URL, às vezes megabytes) é carregada sob
    // demanda pela ordem aberta. Trazê-la aqui inflava o payload global e
    // derrubava a sincronização de todo o sistema.
    supabase.from("ordem_fotos").select("id, ordem_id, etapa, criada_em").order("criada_em"),
    supabase.from("ordem_historico").select("*").order("quando"),
    supabase.from("importacoes").select("*").order("criada_em", { ascending: false }),
    supabase.from("agente_documentos").select("*").order("criado_em", { ascending: false }),
    supabase.from("pagamentos_agente").select("*").order("pago_em", { ascending: false }),
    supabase.from("ordem_evidencias").select("*").order("criada_em"),
    supabase.from("ordem_cobrancas").select("*").order("criado_em"),
    supabase.from("locadora_apelidos").select("*"),
    supabase.from("tabelas_remuneracao").select("*").order("criado_em"),
    supabase.from("itens_remuneracao").select("*").order("posicao"),
    supabase.from("lancamentos_agente").select("*").order("data"),
    supabase.from("configuracoes").select("*"),
    supabase.from("auditoria").select("*").order("criado_em", { ascending: false }).limit(300),
    supabase.from("servicos").select("*").order("posicao"),
    // O RLS já limita aos avisos do próprio usuário conectado.
    supabase.from("notificacoes").select("*").order("criada_em", { ascending: false }).limit(100),
    supabase.from("cancelamentos_ordem").select("*").order("cancelado_em", { ascending: false }),
    // Vistorias: o RLS já limita o que cada perfil enxerga (central, locadora ou agente).
    supabase.from("motos").select("*").order("criada_em", { ascending: false }),
    supabase.from("vistorias").select("*").order("solicitada_em", { ascending: false }),
    supabase.from("vistoria_evidencias").select("*").order("criada_em"),
    supabase.from("vistoria_historico").select("*").order("quando"),
    supabase.from("vistoria_checklist_itens").select("*").order("posicao"),
    supabase.from("vistoria_itens").select("*").order("posicao"),
    supabase.from("vistoria_avarias").select("*").order("criado_em"),
    // Distribuição automática: o RLS entrega só o que cada perfil pode ver.
    supabase.from("distribuicoes").select("*").order("criada_em", { ascending: false }),
    supabase.from("distribuicao_eventos").select("*").order("quando"),
  ]);

  const listaPapeis = conferir(papeis);

  return {
    usuarios: conferir(perfis).map((p) => paraUsuario(p, listaPapeis)),
    locadoras: conferir(locadoras).map(paraLocadora),
    agentes: conferir(agentes).map(paraAgente),
    ordens: conferir(ordens).map(paraOrdem),
    fotos: conferir(fotos).map(paraFoto),
    historico: conferir(historico).map(paraEvento),
    importacoes: conferir(importacoes).map(paraImportacao),
    documentos: conferir(documentos).map(paraDocumento),
    pagamentos: conferir(pagamentos).map(paraPagamento),
    evidencias: conferir(evidencias).map(paraEvidencia),
    cobrancas: conferir(cobrancas).map(paraCobranca),
    apelidos: conferir(apelidos).map(paraApelido),
    servicos: conferir(servicos).map(paraServico),
    tabelas: conferir(tabelas).map(paraTabelaRemuneracao),
    itens: conferir(itens).map(paraItemRemuneracao),
    lancamentos: conferir(lancamentos).map(paraLancamento),
    configuracoes: Object.fromEntries(conferir(configuracoes).map((c) => [c.chave, c.valor])),
    auditoria: conferir(auditoria).map(paraAuditoria),
    notificacoes: conferir(notificacoes).map(paraNotificacao),
    cancelamentos: conferir(cancelamentos).map(paraCancelamento),
    motos: conferir(motos).map(paraMoto),
    vistorias: conferir(vistorias).map(paraVistoria),
    evidenciasVistoria: conferir(evidenciasVistoria).map(paraEvidenciaVistoria),
    historicoVistoria: conferir(historicoVistoria).map(paraEventoVistoria),
    catalogoChecklist: conferir(catalogoChecklist).map(paraItemChecklistCatalogo),
    itensVistoria: conferir(itensVistoria).map(paraItemVistoria),
    avariasVistoria: conferir(avariasVistoria).map(paraAvariaVistoria),
    distribuicoes: conferir(distribuicoes).map(paraDistribuicao),
    eventosDistribuicao: conferir(eventosDistribuicao).map(paraEventoDistribuicao),
  };
}
