/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDistribuicaoRouteImport } from './routes/_app/distribuicao'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppImportacoesRouteImport } from './routes/_app/importacoes'
import { Route as AppImportadorRouteImport } from './routes/_app/importador'
import { Route as AppLocadorasRouteImport } from './routes/_app/locadoras'
import { Route as AppOperacaoRouteImport } from './routes/_app/operacao'
import { Route as AppPortalRouteImport } from './routes/_app/portal'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AppAgenteIndexRouteImport } from './routes/_app/agente/index'
import { Route as AppAgenteIdRouteImport } from './routes/_app/agente/$id'
import { Route as AppAgenteFinanceiroRouteImport } from './routes/_app/agente/financeiro'
import { Route as AppAgenteVistoriasRouteImport } from './routes/_app/agente/vistorias'
import { Route as AppAgentesIndexRouteImport } from './routes/_app/agentes/index'
import { Route as AppAgentesIdRouteImport } from './routes/_app/agentes/$id'
import { Route as AppMotoIdRouteImport } from './routes/_app/moto/$id'
import { Route as AppOrdensIndexRouteImport } from './routes/_app/ordens/index'
import { Route as AppOrdensIdRouteImport } from './routes/_app/ordens/$id'
import { Route as AppVistoriasIndexRouteImport } from './routes/_app/vistorias/index'
import { Route as AppVistoriasIdRouteImport } from './routes/_app/vistorias/$id'
import { Route as AppVistoriasChecklistRouteImport } from './routes/_app/vistorias/checklist'
import { Route as AppVistoriasMotosRouteImport } from './routes/_app/vistorias/motos'
import { Route as AppDocumentosTipoIdRouteImport } from './routes/_app/documentos/$tipo.$id'
import { Route as ApiPublicPushDespacharRouteImport } from './routes/api/public/push/despachar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDistribuicaoRoute = AppDistribuicaoRouteImport.update({
  id: '/distribuicao',
  path: '/distribuicao',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImportacoesRoute = AppImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImportadorRoute = AppImportadorRouteImport.update({
  id: '/importador',
  path: '/importador',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocadorasRoute = AppLocadorasRouteImport.update({
  id: '/locadoras',
  path: '/locadoras',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOperacaoRoute = AppOperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPortalRoute = AppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAgenteIndexRoute = AppAgenteIndexRouteImport.update({
  id: '/agente/',
  path: '/agente/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgenteIdRoute = AppAgenteIdRouteImport.update({
  id: '/agente/$id',
  path: '/agente/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgenteFinanceiroRoute = AppAgenteFinanceiroRouteImport.update({
  id: '/agente/financeiro',
  path: '/agente/financeiro',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgenteVistoriasRoute = AppAgenteVistoriasRouteImport.update({
  id: '/agente/vistorias',
  path: '/agente/vistorias',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentesIndexRoute = AppAgentesIndexRouteImport.update({
  id: '/agentes/',
  path: '/agentes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentesIdRoute = AppAgentesIdRouteImport.update({
  id: '/agentes/$id',
  path: '/agentes/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMotoIdRoute = AppMotoIdRouteImport.update({
  id: '/moto/$id',
  path: '/moto/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdensIndexRoute = AppOrdensIndexRouteImport.update({
  id: '/ordens/',
  path: '/ordens/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdensIdRoute = AppOrdensIdRouteImport.update({
  id: '/ordens/$id',
  path: '/ordens/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVistoriasIndexRoute = AppVistoriasIndexRouteImport.update({
  id: '/vistorias/',
  path: '/vistorias/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVistoriasIdRoute = AppVistoriasIdRouteImport.update({
  id: '/vistorias/$id',
  path: '/vistorias/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVistoriasChecklistRoute = AppVistoriasChecklistRouteImport.update({
  id: '/vistorias/checklist',
  path: '/vistorias/checklist',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVistoriasMotosRoute = AppVistoriasMotosRouteImport.update({
  id: '/vistorias/motos',
  path: '/vistorias/motos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentosTipoIdRoute = AppDocumentosTipoIdRouteImport.update({
  id: '/documentos/$tipo/$id',
  path: '/documentos/$tipo/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiPublicPushDespacharRoute = ApiPublicPushDespacharRouteImport.update({
  id: '/api/public/push/despachar',
  path: '/api/public/push/despachar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AppDashboardRoute
  '/distribuicao': typeof AppDistribuicaoRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/importacoes': typeof AppImportacoesRoute
  '/importador': typeof AppImportadorRoute
  '/locadoras': typeof AppLocadorasRoute
  '/operacao': typeof AppOperacaoRoute
  '/portal': typeof AppPortalRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/agente/$id': typeof AppAgenteIdRoute
  '/agente/financeiro': typeof AppAgenteFinanceiroRoute
  '/agente/vistorias': typeof AppAgenteVistoriasRoute
  '/agentes/$id': typeof AppAgentesIdRoute
  '/moto/$id': typeof AppMotoIdRoute
  '/ordens/$id': typeof AppOrdensIdRoute
  '/vistorias/$id': typeof AppVistoriasIdRoute
  '/vistorias/checklist': typeof AppVistoriasChecklistRoute
  '/vistorias/motos': typeof AppVistoriasMotosRoute
  '/agente/': typeof AppAgenteIndexRoute
  '/agentes/': typeof AppAgentesIndexRoute
  '/ordens/': typeof AppOrdensIndexRoute
  '/vistorias/': typeof AppVistoriasIndexRoute
  '/documentos/$tipo/$id': typeof AppDocumentosTipoIdRoute
  '/api/public/push/despachar': typeof ApiPublicPushDespacharRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AppDashboardRoute
  '/distribuicao': typeof AppDistribuicaoRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/importacoes': typeof AppImportacoesRoute
  '/importador': typeof AppImportadorRoute
  '/locadoras': typeof AppLocadorasRoute
  '/operacao': typeof AppOperacaoRoute
  '/portal': typeof AppPortalRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/agente/$id': typeof AppAgenteIdRoute
  '/agente/financeiro': typeof AppAgenteFinanceiroRoute
  '/agente/vistorias': typeof AppAgenteVistoriasRoute
  '/agentes/$id': typeof AppAgentesIdRoute
  '/moto/$id': typeof AppMotoIdRoute
  '/ordens/$id': typeof AppOrdensIdRoute
  '/vistorias/$id': typeof AppVistoriasIdRoute
  '/vistorias/checklist': typeof AppVistoriasChecklistRoute
  '/vistorias/motos': typeof AppVistoriasMotosRoute
  '/agente': typeof AppAgenteIndexRoute
  '/agentes': typeof AppAgentesIndexRoute
  '/ordens': typeof AppOrdensIndexRoute
  '/vistorias': typeof AppVistoriasIndexRoute
  '/documentos/$tipo/$id': typeof AppDocumentosTipoIdRoute
  '/api/public/push/despachar': typeof ApiPublicPushDespacharRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/distribuicao': typeof AppDistribuicaoRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/importacoes': typeof AppImportacoesRoute
  '/_app/importador': typeof AppImportadorRoute
  '/_app/locadoras': typeof AppLocadorasRoute
  '/_app/operacao': typeof AppOperacaoRoute
  '/_app/portal': typeof AppPortalRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/agente/$id': typeof AppAgenteIdRoute
  '/_app/agente/financeiro': typeof AppAgenteFinanceiroRoute
  '/_app/agente/vistorias': typeof AppAgenteVistoriasRoute
  '/_app/agentes/$id': typeof AppAgentesIdRoute
  '/_app/moto/$id': typeof AppMotoIdRoute
  '/_app/ordens/$id': typeof AppOrdensIdRoute
  '/_app/vistorias/$id': typeof AppVistoriasIdRoute
  '/_app/vistorias/checklist': typeof AppVistoriasChecklistRoute
  '/_app/vistorias/motos': typeof AppVistoriasMotosRoute
  '/_app/agente/': typeof AppAgenteIndexRoute
  '/_app/agentes/': typeof AppAgentesIndexRoute
  '/_app/ordens/': typeof AppOrdensIndexRoute
  '/_app/vistorias/': typeof AppVistoriasIndexRoute
  '/_app/documentos/$tipo/$id': typeof AppDocumentosTipoIdRoute
  '/api/public/push/despachar': typeof ApiPublicPushDespacharRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/distribuicao'
    | '/financeiro'
    | '/importacoes'
    | '/importador'
    | '/locadoras'
    | '/operacao'
    | '/portal'
    | '/relatorios'
    | '/usuarios'
    | '/.mcp/invoke-tool/$tool'
    | '/agente/$id'
    | '/agente/financeiro'
    | '/agente/vistorias'
    | '/agentes/$id'
    | '/moto/$id'
    | '/ordens/$id'
    | '/vistorias/$id'
    | '/vistorias/checklist'
    | '/vistorias/motos'
    | '/agente/'
    | '/agentes/'
    | '/ordens/'
    | '/vistorias/'
    | '/documentos/$tipo/$id'
    | '/api/public/push/despachar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/distribuicao'
    | '/financeiro'
    | '/importacoes'
    | '/importador'
    | '/locadoras'
    | '/operacao'
    | '/portal'
    | '/relatorios'
    | '/usuarios'
    | '/.mcp/invoke-tool/$tool'
    | '/agente/$id'
    | '/agente/financeiro'
    | '/agente/vistorias'
    | '/agentes/$id'
    | '/moto/$id'
    | '/ordens/$id'
    | '/vistorias/$id'
    | '/vistorias/checklist'
    | '/vistorias/motos'
    | '/agente'
    | '/agentes'
    | '/ordens'
    | '/vistorias'
    | '/documentos/$tipo/$id'
    | '/api/public/push/despachar'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/entrar'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/dashboard'
    | '/_app/distribuicao'
    | '/_app/financeiro'
    | '/_app/importacoes'
    | '/_app/importador'
    | '/_app/locadoras'
    | '/_app/operacao'
    | '/_app/portal'
    | '/_app/relatorios'
    | '/_app/usuarios'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/agente/$id'
    | '/_app/agente/financeiro'
    | '/_app/agente/vistorias'
    | '/_app/agentes/$id'
    | '/_app/moto/$id'
    | '/_app/ordens/$id'
    | '/_app/vistorias/$id'
    | '/_app/vistorias/checklist'
    | '/_app/vistorias/motos'
    | '/_app/agente/'
    | '/_app/agentes/'
    | '/_app/ordens/'
    | '/_app/vistorias/'
    | '/_app/documentos/$tipo/$id'
    | '/api/public/push/despachar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicPushDespacharRoute: typeof ApiPublicPushDespacharRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/distribuicao': {
      id: '/_app/distribuicao'
      path: '/distribuicao'
      fullPath: '/distribuicao'
      preLoaderRoute: typeof AppDistribuicaoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/importacoes': {
      id: '/_app/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof AppImportacoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/importador': {
      id: '/_app/importador'
      path: '/importador'
      fullPath: '/importador'
      preLoaderRoute: typeof AppImportadorRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/locadoras': {
      id: '/_app/locadoras'
      path: '/locadoras'
      fullPath: '/locadoras'
      preLoaderRoute: typeof AppLocadorasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/operacao': {
      id: '/_app/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof AppOperacaoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/portal': {
      id: '/_app/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AppPortalRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agente/': {
      id: '/_app/agente/'
      path: '/agente'
      fullPath: '/agente/'
      preLoaderRoute: typeof AppAgenteIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agente/$id': {
      id: '/_app/agente/$id'
      path: '/agente/$id'
      fullPath: '/agente/$id'
      preLoaderRoute: typeof AppAgenteIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agente/financeiro': {
      id: '/_app/agente/financeiro'
      path: '/agente/financeiro'
      fullPath: '/agente/financeiro'
      preLoaderRoute: typeof AppAgenteFinanceiroRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agente/vistorias': {
      id: '/_app/agente/vistorias'
      path: '/agente/vistorias'
      fullPath: '/agente/vistorias'
      preLoaderRoute: typeof AppAgenteVistoriasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agentes/': {
      id: '/_app/agentes/'
      path: '/agentes'
      fullPath: '/agentes/'
      preLoaderRoute: typeof AppAgentesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agentes/$id': {
      id: '/_app/agentes/$id'
      path: '/agentes/$id'
      fullPath: '/agentes/$id'
      preLoaderRoute: typeof AppAgentesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/moto/$id': {
      id: '/_app/moto/$id'
      path: '/moto/$id'
      fullPath: '/moto/$id'
      preLoaderRoute: typeof AppMotoIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ordens/': {
      id: '/_app/ordens/'
      path: '/ordens'
      fullPath: '/ordens/'
      preLoaderRoute: typeof AppOrdensIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ordens/$id': {
      id: '/_app/ordens/$id'
      path: '/ordens/$id'
      fullPath: '/ordens/$id'
      preLoaderRoute: typeof AppOrdensIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/vistorias/': {
      id: '/_app/vistorias/'
      path: '/vistorias'
      fullPath: '/vistorias/'
      preLoaderRoute: typeof AppVistoriasIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/vistorias/$id': {
      id: '/_app/vistorias/$id'
      path: '/vistorias/$id'
      fullPath: '/vistorias/$id'
      preLoaderRoute: typeof AppVistoriasIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/vistorias/checklist': {
      id: '/_app/vistorias/checklist'
      path: '/vistorias/checklist'
      fullPath: '/vistorias/checklist'
      preLoaderRoute: typeof AppVistoriasChecklistRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/vistorias/motos': {
      id: '/_app/vistorias/motos'
      path: '/vistorias/motos'
      fullPath: '/vistorias/motos'
      preLoaderRoute: typeof AppVistoriasMotosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/documentos/$tipo/$id': {
      id: '/_app/documentos/$tipo/$id'
      path: '/documentos/$tipo/$id'
      fullPath: '/documentos/$tipo/$id'
      preLoaderRoute: typeof AppDocumentosTipoIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/public/push/despachar': {
      id: '/api/public/push/despachar'
      path: '/api/public/push/despachar'
      fullPath: '/api/public/push/despachar'
      preLoaderRoute: typeof ApiPublicPushDespacharRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDistribuicaoRoute: typeof AppDistribuicaoRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppImportacoesRoute: typeof AppImportacoesRoute
  AppImportadorRoute: typeof AppImportadorRoute
  AppLocadorasRoute: typeof AppLocadorasRoute
  AppOperacaoRoute: typeof AppOperacaoRoute
  AppPortalRoute: typeof AppPortalRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppAgenteIdRoute: typeof AppAgenteIdRoute
  AppAgenteFinanceiroRoute: typeof AppAgenteFinanceiroRoute
  AppAgenteVistoriasRoute: typeof AppAgenteVistoriasRoute
  AppAgentesIdRoute: typeof AppAgentesIdRoute
  AppMotoIdRoute: typeof AppMotoIdRoute
  AppOrdensIdRoute: typeof AppOrdensIdRoute
  AppVistoriasIdRoute: typeof AppVistoriasIdRoute
  AppVistoriasChecklistRoute: typeof AppVistoriasChecklistRoute
  AppVistoriasMotosRoute: typeof AppVistoriasMotosRoute
  AppAgenteIndexRoute: typeof AppAgenteIndexRoute
  AppAgentesIndexRoute: typeof AppAgentesIndexRoute
  AppOrdensIndexRoute: typeof AppOrdensIndexRoute
  AppVistoriasIndexRoute: typeof AppVistoriasIndexRoute
  AppDocumentosTipoIdRoute: typeof AppDocumentosTipoIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDistribuicaoRoute: AppDistribuicaoRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppImportacoesRoute: AppImportacoesRoute,
  AppImportadorRoute: AppImportadorRoute,
  AppLocadorasRoute: AppLocadorasRoute,
  AppOperacaoRoute: AppOperacaoRoute,
  AppPortalRoute: AppPortalRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppAgenteIdRoute: AppAgenteIdRoute,
  AppAgenteFinanceiroRoute: AppAgenteFinanceiroRoute,
  AppAgenteVistoriasRoute: AppAgenteVistoriasRoute,
  AppAgentesIdRoute: AppAgentesIdRoute,
  AppMotoIdRoute: AppMotoIdRoute,
  AppOrdensIdRoute: AppOrdensIdRoute,
  AppVistoriasIdRoute: AppVistoriasIdRoute,
  AppVistoriasChecklistRoute: AppVistoriasChecklistRoute,
  AppVistoriasMotosRoute: AppVistoriasMotosRoute,
  AppAgenteIndexRoute: AppAgenteIndexRoute,
  AppAgentesIndexRoute: AppAgentesIndexRoute,
  AppOrdensIndexRoute: AppOrdensIndexRoute,
  AppVistoriasIndexRoute: AppVistoriasIndexRoute,
  AppDocumentosTipoIdRoute: AppDocumentosTipoIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  EntrarRoute: EntrarRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicPushDespacharRoute: ApiPublicPushDespacharRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
